# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Euskovid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for euskovid
 
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Charts'
  
end
